
get_script_dir <- function() {
  args <- commandArgs(trailingOnly = FALSE)
  file_flag <- '--file='
  path <- sub(file_flag, '', args[grepl(file_flag, args)])
  if (length(path) > 0) dirname(normalizePath(path[1])) else getwd()
}
SCRIPT_DIR <- get_script_dir()
PROJ_ROOT <- normalizePath(file.path(SCRIPT_DIR, '..'), winslash = '/', mustWork = FALSE)
source(file.path(PROJ_ROOT, 'helpers', 'figure_plot_helpers.R'))
source(file.path(PROJ_ROOT, 'helpers', 'figure34_helpers.R'))
OUT_DIR <- file.path(PROJ_ROOT, 'outputs', 'main_figures')
dir.create(OUT_DIR, showWarnings = FALSE, recursive = TRUE)
IN_PER_GENOME <- file.path(PROJ_ROOT, 'per_genome.csv')
IN_PER_INVERSION <- file.path(PROJ_ROOT, 'per_inversion.csv')


############################################################
## Figure 4 (main)
############################################################
IN_KAKS_SHIFT <- file.path(PROJ_ROOT, 'inversion_kaks_shift.csv')
if (!file.exists(IN_KAKS_SHIFT)) stop('Figure 4 expects inversion_kaks_shift.csv in the package root.', call. = FALSE)
per_inv <- load_per_inversion_age(IN_PER_INVERSION)
require_columns(per_inv, c('gene_density_ratio_genome','te_prop_union','pi_ratio_inv_flank'), 'per_inv')
len_gd <- summarise_by_lenbin(per_inv %>% filter(!is.na(gene_density_ratio_genome)), gene_density_ratio_genome)
fig4a <- plot_lenbin_trait(len_gd, ylab = 'Gene density (inversion / genome)', hline1 = 1)
fig4b <- plot_lenclass_box(per_inv, gene_density_ratio_genome, ylab = 'Gene density (inversion / genome)', hline1 = 1)
age_gd <- summarise_by_agebin(per_inv %>% filter(!is.na(gene_density_ratio_genome)), gene_density_ratio_genome)
fig4c <- plot_agebin_trait(age_gd, ylab = 'Gene density (inversion / genome)', hline1 = 1)
len_te <- summarise_by_lenbin(per_inv %>% filter(!is.na(te_prop_union), te_prop_union >= 0), te_prop_union)
fig4d <- plot_lenbin_trait(len_te, ylab = 'TE proportion')
per_inv_flank_w <- per_inv %>% filter(!is.na(pi_ratio_inv_flank), pi_ratio_inv_flank > 0) %>% mutate(len_bin_left = seq(2,8,1)[cut(log10_len, breaks = seq(2,8,1), labels = FALSE, include.lowest = TRUE, right = FALSE)]) %>% filter(!is.na(len_bin_left)) %>% winsorize_by_group_bin(pi_ratio_inv_flank, group_col = 'kingdom', bin_col = len_bin_left, p = 0.999)
len_pi <- summarise_by_lenbin(per_inv_flank_w, pi_ratio_inv_flank)
fig4e <- plot_lenbin_trait(len_pi, ylab = expression(pi[inversion] / pi[flank]), hline1 = 1)
per_inv_te_w <- per_inv %>% filter(!is.na(pi_ratio_inv_flank), pi_ratio_inv_flank > 0, !is.na(te_prop_union), te_prop_union >= 0, te_prop_union <= 1) %>% winsorize_by_group_bin(pi_ratio_inv_flank, group_col = 'kingdom', bin_col = te_prop_union, p = 0.999)
te_pi <- summarise_by_tebin(per_inv_te_w, pi_ratio_inv_flank)
fig4f <- plot_tebin_trait(te_pi, ylab = expression(pi[inversion] / pi[flank]), hline1 = 1)
kaks_shift <- readr::read_tsv(IN_KAKS_SHIFT, show_col_types = FALSE) %>% mutate(kaks_shift_ratio_median = suppressWarnings(as.numeric(kaks_shift_ratio_median)), kaks_shift_ratio_p90 = suppressWarnings(as.numeric(kaks_shift_ratio_p90)), n_genes_found = suppressWarnings(as.numeric(n_genes_found)))
inv_meta_shift <- per_inv %>% transmute(sample_id, inv_id, kingdom, inv_len_bp, size_bin = case_when(inv_len_bp < 1e5 ~ 'small', inv_len_bp < 1e6 ~ 'medium', TRUE ~ 'large'), size_bin = factor(size_bin, levels = c('small','medium','large')))
shift_df <- kaks_shift %>% inner_join(inv_meta_shift, by = c('sample_id','inv_id')) %>% filter(kingdom %in% c('Metazoa','Viridiplantae'), status == 'ok', !is.na(size_bin), !is.na(n_genes_found), n_genes_found >= 1)
fig4g <- plot_density_kingdom_ratio(shift_df, 'kaks_shift_ratio_p90', xlab = expression(paste('Relative ', omega, ' of inversion genes (90th percentile)')), xlim = c(0,2))
fig4h <- plot_density_size(shift_df, 'kaks_shift_ratio_p90', xlab = expression(paste('Relative ', omega, ' of inversion genes (90th percentile)')), xlim = c(0,2), facet_by_kingdom = TRUE)
row3 <- fig4g + fig4h + plot_layout(widths = c(1,2))
Fig4 <- (fig4a | fig4b | fig4c) / (fig4d | fig4e | fig4f) / row3 + plot_annotation(tag_levels = 'a', theme = theme(plot.tag = element_text(face = 'bold', size = 8)))
save_pdf(Fig4, 'Fig4.pdf', 180, 180); save_png(Fig4, 'Fig4.png', 180, 180, dpi = 300); writeLines(capture.output(sessionInfo()), file.path(OUT_DIR, 'Fig4_sessionInfo.txt'))
