#!/usr/bin/env python3
"""Generate bilingual README files from repository structure."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Folder names intentionally follow existing repository naming.
SECTION_ORDER = [
    "0data_prepare",
    "1assmbly",
    "2SV_identify",
    "3Genome_annotation",
    "4Post_analysis",
]

EN_DESCRIPTIONS = {
    "0data_prepare": "Data download and preprocessing",
    "1assmbly": "HiFi/Hi-C assembly pipelines",
    "2SV_identify": "SV and inversion identification",
    "3Genome_annotation": "Repeat masking and genome annotation",
    "4Post_analysis": "Post-analysis and evolutionary summaries",
}

ZH_DESCRIPTIONS = {
    "0data_prepare": "数据下载与预处理",
    "1assmbly": "HiFi/Hi-C 组装流程",
    "2SV_identify": "SV 与倒位识别",
    "3Genome_annotation": "重复序列处理与基因组注释",
    "4Post_analysis": "后续分析与进化统计",
}


@dataclass(frozen=True)
class SectionInfo:
    name: str
    script_count: int


def count_scripts(folder: Path) -> int:
    patterns = ("*.py", "*.sh")
    return sum(1 for pattern in patterns for _ in folder.glob(pattern))


def collect_sections() -> list[SectionInfo]:
    sections: list[SectionInfo] = []
    for name in SECTION_ORDER:
        path = ROOT / name
        if path.is_dir():
            sections.append(SectionInfo(name=name, script_count=count_scripts(path)))
    return sections


def render_english(sections: list[SectionInfo]) -> str:
    lines = [
        "# Inversion Survey Project",
        "",
        "[中文版说明（Chinese README）](README_zh.md)",
        "",
        "This README is auto-generated by `scripts/generate_readme.py`.",
        "",
        "This repository provides workflows for characterizing chromosomal inversions "
        "using haplotype-resolved assemblies across eukaryotic species.",
        "",
        "## Pipeline modules",
        "",
    ]

    for sec in sections:
        desc = EN_DESCRIPTIONS.get(sec.name, "Pipeline module")
        lines.append(f"- `{sec.name}/`: {desc} ({sec.script_count} scripts: `.py`/`.sh`).")

    lines.extend(
        [
            "",
            "## Typical usage",
            "",
            "1. Prepare data under `0data_prepare/`.",
            "2. Run assembly workflows under `1assmbly/`.",
            "3. Identify inversions under `2SV_identify/`.",
            "4. Annotate genomes under `3Genome_annotation/`.",
            "5. Perform downstream analyses under `4Post_analysis/`.",
            "",
            "## Automation",
            "",
            "- GitHub Actions workflow: `.github/workflows/auto-update-readme.yml`.",
            "- Triggered on pushes affecting scripts, manual dispatch, and weekly schedule.",
            "",
            "## License",
            "",
            "See [LICENSE](LICENSE).",
            "",
        ]
    )

    return "\n".join(lines)


def render_chinese(sections: list[SectionInfo]) -> str:
    lines = [
        "# Inversion Survey Project（中文说明）",
        "",
        "[English README](README.md)",
        "",
        "本说明由 `scripts/generate_readme.py` 自动生成。",
        "",
        "本仓库提供基于单倍型分辨组装的倒位识别流程，适用于多类真核生物数据分析。",
        "",
        "## 流程模块",
        "",
    ]

    for sec in sections:
        desc = ZH_DESCRIPTIONS.get(sec.name, "流程模块")
        lines.append(f"- `{sec.name}/`：{desc}（`.py`/`.sh` 脚本 {sec.script_count} 个）。")

    lines.extend(
        [
            "",
            "## 典型使用顺序",
            "",
            "1. 在 `0data_prepare/` 完成数据准备。",
            "2. 在 `1assmbly/` 执行组装流程。",
            "3. 在 `2SV_identify/` 进行倒位识别。",
            "4. 在 `3Genome_annotation/` 完成注释处理。",
            "5. 在 `4Post_analysis/` 进行下游分析。",
            "",
            "## 自动化",
            "",
            "- GitHub Actions 工作流：`.github/workflows/auto-update-readme.yml`。",
            "- 在脚本变更、手动触发和每周定时任务时自动更新 README。",
            "",
            "## 许可证",
            "",
            "详见 [LICENSE](LICENSE)。",
            "",
        ]
    )

    return "\n".join(lines)


def main() -> None:
    sections = collect_sections()
    (ROOT / "README.md").write_text(render_english(sections), encoding="utf-8")
    (ROOT / "README_zh.md").write_text(render_chinese(sections), encoding="utf-8")


if __name__ == "__main__":
    main()
